package com.warsim.frontline.api.classes;

public enum DeploymentFailureReason {
    NONE,
    DISABLED,
    NOT_PLAYING,
    INVALID_MATCH,
    INVALID_STATE,
    NO_LOCAL_SESSION,
    NO_ACTIVE_PARTICIPANT,
    NO_ROSTER_ASSIGNMENT,
    NO_CLASS_SELECTED,
    CLASS_LIMIT_REACHED,
    PROVIDER_UNAVAILABLE,
    LOADOUT_INVALID,
    TOKEN_INVALID,
    SPAWN_UNAVAILABLE,
    TICKET_UNAVAILABLE,
    TICKETS_DEPLETED,
    STALE_CONTEXT,
    ALREADY_DEPLOYING,
    ALREADY_ALIVE,
    ROLLBACK_FAILED,
    INTERNAL_ERROR,
    UNIMPLEMENTED_SPAWN_TYPE
}
