package com.warsim.frontline.api.weapon;

public enum ShotOutcome {
    FIRED_MISS, FIRED_BLOCKED, FIRED_BODY_HIT, FIRED_HEAD_HIT, FRIENDLY_BLOCKED,
    REJECTED_NOT_PLAYING, REJECTED_NOT_ACTIVE, REJECTED_NO_ASSIGNMENT,
    REJECTED_INVALID_ITEM, REJECTED_COOLDOWN, REJECTED_EMPTY,
    REJECTED_RELOADING, REJECTED_INVALID_STATE, REJECTED_INTERNAL_ERROR
}
