package com.warsim.frontline.api.weapon;

public enum WeaponFailureReason {
    NONE, DISABLED, NOT_PLAYING, NOT_ACTIVE, NO_ASSIGNMENT, INVALID_ITEM,
    COOLDOWN, EMPTY, RELOADING, FULL_MAGAZINE, NO_RESERVE, INVALID_STATE,
    STALE_MATCH, BLOCK_TRACE_FAILED, INTERNAL_ERROR
}
